manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: moergo-sc
      url-base: https://github.com/moergo-sc
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: infely
      url-base: https://github.com/infely
  projects:
    - name: zmk
      remote: moergo-sc
      revision: go60-zmk0.3.0
      import: app/west.yml
    - name: nice-view-battery
      remote: infely
      revision: main
  self:
    path: boards
